### ISSUE TITLE
看不到1.4.1版本的代码

### ISSUE THREAD

**Issue by fcinfo** [daixinkai/feign.net#14]
1.4.1版本变动较大，有没有代码和例子？

**Comment by fcinfo** [comment]
d

**Comment by daixinkai** [comment]
这个尽量兼容1.3.1+了,请问是有哪报错吗?

**Comment by fcinfo** [comment]
不好意思，是我少下了一个依赖。谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月10日 20:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [daixinkai/feign.net] 看不到1.4.1版本的代码 (Issue #14) |

这个尽量兼容1.3.1+了,请问是有哪报错吗?
