### ISSUE TITLE
SteeltoeServiceDiscovery 服务发现的时候没有过滤不健康节点

### ISSUE THREAD

**Issue by xiaodaidi1** [daixinkai/feign.net#2]
SteeltoeServiceDiscovery.cs

```
public IList<IServiceInstance> GetServiceInstances(string serviceId)
        {
            return _discoveryClient.GetInstances(serviceId).Select(s => new SteeltoeServiceInstance(s)).ToList<IServiceInstance>();
        }
```

这个函数有个bug
GetInstances返回节点的时候,没有过滤不健康的节点.
所以集群里有机器下线了,feign请求就有概率失败

**Comment by daixinkai** [comment]
> SteeltoeServiceDiscovery.cs
> 
> ```
> public IList<IServiceInstance> GetServiceInstances(string serviceId)
>         {
>             return _discoveryClient.GetInstances(serviceId).Select(s => new SteeltoeServiceInstance(s)).ToList<IServiceInstance>();
>         }
> ```
> 
> 这个函数有个bug
> GetInstances返回节点的时候,没有过滤不健康的节点.
> 所以集群里有机器下线了,feign请求就有概率失败

默认启用了缓存,10分钟失效,是不是缓存未到期?
如果排除缓存的原因的话可以查查Steeltoe的文档,看看相关配置(比如过滤不健康节点)

**Comment by daixinkai** [comment]
> SteeltoeServiceDiscovery.cs
> 
> ```
> public IList<IServiceInstance> GetServiceInstances(string serviceId)
>         {
>             return _discoveryClient.GetInstances(serviceId).Select(s => new SteeltoeServiceInstance(s)).ToList<IServiceInstance>();
>         }
> ```
> 
> 这个函数有个bug
> GetInstances返回节点的时候,没有过滤不健康的节点.
> 所以集群里有机器下线了,feign请求就有概率失败

试了一下,以consul为例:
  "consul": {
    "host": "xxxxxxx",
    "port": "8500",
    "discovery": {
      "register": false,
      "queryPassing": true
    }
  }
添加queryPassing=true可以过滤错误节点

**Comment by spacestime** [comment]
我使用了SteeltoeServiceDiscovery3.0.1

**Comment by daixinkai** [comment]
> 我使用了SteeltoeServiceDiscovery3.0.1
> 
> ```
> //Steeltoe
>         services.AddDiscoveryClient(Configuration);
>         //Feign
>         services.AddFeignClients().AddSteeltoe();
> ```
> 
> 第一个是可以访问服务，第二个不行，请问还需要配置什么吗？
> [HttpGet("Get1")]
> public async Task Get1()
> {
> var client = new HttpClient(_handler, false);
> return await client.GetStringAsync("http://agent-service/weatherforecast");
> }
> 
> ```
>     [HttpGet("Get")]
>     public async Task<IEnumerable<WeatherForecast>> Get2()
>     {
>         return await this.AngleSharpTestService.GetHtmlAsync();
>     }
> ```

请问报什么错呢?
SteeltoeServiceDiscovery 3.0 版本需要引入 Steeltoe.Discovery.Consul 3.0 或者 Steeltoe.Discovery.Eureka 3.0 才行
