### ISSUE TITLE
httpclient在core 2.1以后推荐用factory 初始化

### ISSUE THREAD

**Issue by xiaodaidi1** [daixinkai/feign.net#4]
```
HttpClient = new FeignHttpClient(new FeignDelegatingHandler(serviceDiscoveryHttpClientHandler));
```
好像还是使用了传统了方式new了client,
这个方式会带来性能问题
core 2.1以后引入了 HttpClientFactory, 并且引入了 HttpClientBuilder, 应该可以替代部分现有提供的pipeline
考虑升级一下版本?

**Comment by daixinkai** [comment]
> ```
> HttpClient = new FeignHttpClient(new FeignDelegatingHandler(serviceDiscoveryHttpClientHandler));
> ```
> 
> 好像还是使用了传统了方式new了client,
> 这个方式会带来性能问题
> core 2.1以后引入了 HttpClientFactory, 并且引入了 HttpClientBuilder, 应该可以替代部分现有提供的pipeline
> 考虑升级一下版本?

怕影响性能的话可以使用单例模式  FeignClientLifetime.Singleton

IHttpClientFactory与IHttpClientBuilder都定义在Microsoft.Extensions.Http中,目前并不考虑直接引用,不过可以使用类似 IHttpClientProvider 的方式引入进来.

**Comment by daixinkai** [comment]
> ```
> HttpClient = new FeignHttpClient(new FeignDelegatingHandler(serviceDiscoveryHttpClientHandler));
> ```
> 
> 好像还是使用了传统了方式new了client,
> 这个方式会带来性能问题
> core 2.1以后引入了 HttpClientFactory, 并且引入了 HttpClientBuilder, 应该可以替代部分现有提供的pipeline
> 考虑升级一下版本?

基于事件驱动pipeline的方式确实是不大好``
