### ISSUE TITLE
IDiscoveryClient  已经迁移

### ISSUE THREAD

**Issue by niuniu007** [daixinkai/feign.net#5]
Steeltoe.Common 3.0.0  中已经将   IDiscoveryClient 迁移到  Steeltoe.Discovery 空间下了

**Comment by daixinkai** [comment]
> Steeltoe.Common 3.0.0 中已经将 IDiscoveryClient 迁移到 Steeltoe.Discovery 空间下了

netstandard2.1 已经支持!
