### ISSUE TITLE
SteeltoeServiceDiscovery3.0.1 请教一下，还需要什么配置？

### ISSUE THREAD

**Issue by spacestime** [daixinkai/feign.net#6]
我使用了SteeltoeServiceDiscovery3.0.1

//Steeltoe
        services.AddDiscoveryClient(Configuration);
        //Feign
        services.AddFeignClients().AddSteeltoe();

第一个是可以访问服务，第二个不行，请问还需要配置什么吗？

[HttpGet("Get1")]
public async Task Get1()
{
var client = new HttpClient(_handler, false);
return await client.GetStringAsync("http://agent-service/weatherforecast");
}
    [HttpGet("Get")]
    public async Task<IEnumerable<WeatherForecast>> Get2()
    {
        return await this.AngleSharpTestService.GetHtmlAsync();
    }

**Comment by daixinkai** [comment]
> 我使用了SteeltoeServiceDiscovery3.0.1
> 
> //Steeltoe
> services.AddDiscoveryClient(Configuration);
> //Feign
> services.AddFeignClients().AddSteeltoe();
> 
> 第一个是可以访问服务，第二个不行，请问还需要配置什么吗？
> 
> [HttpGet("Get1")]
> public async Task Get1()
> {
> var client = new HttpClient(_handler, false);
> return await client.GetStringAsync("http://agent-service/weatherforecast");
> }
> [HttpGet("Get")]
> public async Task<IEnumerable> Get2()
> {
> return await this.AngleSharpTestService.GetHtmlAsync();
> }

请问报什么错呢?
SteeltoeServiceDiscovery 3.0 版本需要引入 Steeltoe.Discovery.Consul 3.0 或者 Steeltoe.Discovery.Eureka 3.0 才行

**Comment by spacestime** [comment]
Feign.Proxy.FeignProxyHttpClientHandler<TService>.SendInternalAsync(FeignHttpRequestMessage request, CancellationToken cancellationToken) in FeignProxyHttpClientHandler.cs
-
                    _logger?.LogError(e, "Exception during SendAsync()");
                }
                if (e is HttpRequestException)
                {
                    FeignHttpRequestException feignHttpRequestException = new FeignHttpRequestException(_feignClient, request, (HttpRequestException)e);
                    ExceptionDispatchInfo exceptionDispatchInfo = ExceptionDispatchInfo.Capture(feignHttpRequestException);
                    exceptionDispatchInfo.Throw();
                }
                throw;
            }
            finally
            {
                request.RequestUri = current;
System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
Feign.Proxy.FeignClientHttpProxy<TService>.SendAsyncInternal(FeignClientHttpRequest request) in FeignClientHttpProxy.Request.cs
-
                    HttpContent httpContent = request.GetHttpContent();
                    if (httpContent != null)
                    {
                        httpRequestMessage.Content = httpContent;
                    }
                }
                return await HttpClient.SendAsync(httpRequestMessage, request.CompletionOption)
#if CONFIGUREAWAIT_FALSE
           .ConfigureAwait(false)
#endif
                    ;
            }
        }
Feign.Proxy.FeignClientHttpProxy<TService>.GetResponseMessageAsync(FeignClientHttpRequest request) in FeignClientHttpProxy.Request.cs
-
        }
        private async Task<HttpResponseMessage> GetResponseMessageAsync(FeignClientHttpRequest request)
        {
            try
            {
                return await SendAsyncInternal(request)
#if CONFIGUREAWAIT_FALSE
           .ConfigureAwait(false)
#endif
                    ;
            }
            catch (TerminatedRequestException)
Feign.Proxy.FeignClientHttpProxy<TService>.SendAsync<TResult>(FeignClientHttpRequest request) in FeignClientHttpProxy.Request.cs
-
           ;
            }
        }
        protected virtual async Task<TResult> SendAsync<TResult>(FeignClientHttpRequest request)
        {
            HttpResponseMessage response = await GetResponseMessageAsync(request)
#if CONFIGUREAWAIT_FALSE
           .ConfigureAwait(false)
#endif
                ;
            using (response)
Feign.TestWeb.NETCORE31.Controllers.WeatherForecastController.Get2() in WeatherForecastController.cs
-
            return await client.GetStringAsync("http://agent-service/weatherforecast");
        }
        [HttpGet("Get")]
        public async Task<IEnumerable<WeatherForecast>> Get2()
        {
            return await this.AngleSharpTestService.GetHtmlAsync();
        }
        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
lambda_method(Closure , object )
Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by spacestime** [comment]
使用Steeltoe官方的方法是可以拿到值的，
      private readonly ILogger<WeatherForecastController> _logger;

        IAngleSharpTestService AngleSharpTestService;

        DiscoveryHttpClientHandler _handler;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IDiscoveryClient client, IAngleSharpTestService angleSharpTestService)
        {
            _logger = logger;
            _handler = new DiscoveryHttpClientHandler(client);
            this.AngleSharpTestService = angleSharpTestService;
        }

        [HttpGet("Get1")]
        public async Task<String> Get1()
        {
            var client = new HttpClient(_handler, false);
            return await client.GetStringAsync("http://agent-service/weatherforecast");
        }

**Comment by daixinkai** [comment]
> 使用Steeltoe官方的方法是可以拿到值的，
> private readonly ILogger _logger;
> 
> ```
>     IAngleSharpTestService AngleSharpTestService;
> 
>     DiscoveryHttpClientHandler _handler;
> 
>     public WeatherForecastController(ILogger<WeatherForecastController> logger, IDiscoveryClient client, IAngleSharpTestService angleSharpTestService)
>     {
>         _logger = logger;
>         _handler = new DiscoveryHttpClientHandler(client);
>         this.AngleSharpTestService = angleSharpTestService;
>     }
> 
>     [HttpGet("Get1")]
>     public async Task<String> Get1()
>     {
>         var client = new HttpClient(_handler, false);
>         return await client.GetStringAsync("http://agent-service/weatherforecast");
>     }
> ```

看不出啥问题,方便把 "IAngleSharpTestService" 这个接口定义发来看看吗? 还有 Steeltoe 的配置文件

**Comment by spacestime** [comment]
配置如下

// begin - spring cloud eureka settings
  "spring": {
    "application": {
      "name": "client-service"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/",
      "shouldFetchRegistry": true,
      "validateCertificates": false // 不需要获取注册信息，只提供服务
    },
    "instance": {
      "port": 8010
      //"preferIpAddress": true,
      //"instanceId": "client-service-container:8010"
    }
  },
  //"services": {
  //  "base-service": {
  //    "url": "http://client-service/"
  //  }
  //},
  // end - spring cloud eureka settings

**Comment by spacestime** [comment]
> > 使用Steeltoe官方的方法是可以拿到值的，
> > private readonly ILogger _logger;
> > ```
> >     IAngleSharpTestService AngleSharpTestService;
> > 
> >     DiscoveryHttpClientHandler _handler;
> > 
> >     public WeatherForecastController(ILogger<WeatherForecastController> logger, IDiscoveryClient client, IAngleSharpTestService angleSharpTestService)
> >     {
> >         _logger = logger;
> >         _handler = new DiscoveryHttpClientHandler(client);
> >         this.AngleSharpTestService = angleSharpTestService;
> >     }
> > 
> >     [HttpGet("Get1")]
> >     public async Task<String> Get1()
> >     {
> >         var client = new HttpClient(_handler, false);
> >         return await client.GetStringAsync("http://agent-service/weatherforecast");
> >     }
> > ```
> 
> 看不出啥问题,方便把 "IAngleSharpTestService" 这个接口定义发来看看吗? 还有 Steeltoe 的配置文件
[知道问题出在什么地方了，如下，感谢@daixinkai
    //**Steeltoe错误的写方法   不需要Url**
    //[FeignClient("agent-service", Url = "http://agent-service")]
    //**Steeltoe正确的写方法  agent-service 是服务名称**
    [FeignClient("agent-service")]
