### ISSUE TITLE
降级回调方法里面能获取到异常吗？我看接口里面没有定义

### ISSUE THREAD

**Issue by z514987467** [daixinkai/feign.net#9]
降级回调方法里面能获取到异常吗？我看接口里面没有定义。
```
     /// <summary>
    /// 一个接口,表示服务降级提供者
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public interface IFallbackFactory</*out*/ T>
    {
        T GetFallback();
        void ReleaseFallback(T fallback);
    }
```

**Comment by daixinkai** [comment]
> 降级回调方法里面能获取到异常吗？我看接口里面没有定义。
> 
> ```
>      /// <summary>
>     /// 一个接口,表示服务降级提供者
>     /// </summary>
>     /// <typeparam name="T"></typeparam>
>     public interface IFallbackFactory</*out*/ T>
>     {
>         T GetFallback();
>         void ReleaseFallback(T fallback);
>     }
> ```

好像没这功能,您是啥场景需要这个呢?

**Comment by z514987467** [comment]
> > 降级回调方法里面能获取到异常吗？我看接口里面没有定义。
> > ```
> >      /// <summary>
> >     /// 一个接口,表示服务降级提供者
> >     /// </summary>
> >     /// <typeparam name="T"></typeparam>
> >     public interface IFallbackFactory</*out*/ T>
> >     {
> >         T GetFallback();
> >         void ReleaseFallback(T fallback);
> >     }
> > ```
> 
> 好像没这功能,您是啥场景需要这个呢?
> 这个降级功能不完善,没有熔断功能,可以集成Polly试试

比如A调用B服务，在B服务异常时（服务不可用或者服务地址写错），需要打印错误日志，微服务框架用的spring cloud alibaba，不知道能不能用Polly

**Comment by z514987467** [comment]
> > 降级回调方法里面能获取到异常吗？我看接口里面没有定义。
> > ```
> >      /// <summary>
> >     /// 一个接口,表示服务降级提供者
> >     /// </summary>
> >     /// <typeparam name="T"></typeparam>
> >     public interface IFallbackFactory</*out*/ T>
> >     {
> >         T GetFallback();
> >         void ReleaseFallback(T fallback);
> >     }
> > ```
> 
> 好像没这功能,您是啥场景需要这个呢?
> 这个降级功能不完善,没有熔断功能,可以集成Polly试试

比如A调用B服务，在B服务异常时（服务不可用或者服务地址写错），需要打印错误日志，微服务框架用的spring cloud alibaba，不知道能不能用Polly

**Comment by z514987467** [comment]
> > 降级回调方法里面能获取到异常吗？我看接口里面没有定义。
> > ```
> >      /// <summary>
> >     /// 一个接口,表示服务降级提供者
> >     /// </summary>
> >     /// <typeparam name="T"></typeparam>
> >     public interface IFallbackFactory</*out*/ T>
> >     {
> >         T GetFallback();
> >         void ReleaseFallback(T fallback);
> >     }
> > ```
> 
> 好像没这功能,您是啥场景需要这个呢?
> 这个降级功能不完善,没有熔断功能,可以集成Polly试试

比如A调用B服务，在B服务异常时（服务不可用或者服务地址写错），需要打印错误日志，微服务框架用的spring cloud alibaba，不知道能不能用Polly

**Comment by daixinkai** [comment]
> > > 降级回调方法里面能获取到异常吗？我看接口里面没有定义。
> > > ```
> > >      /// <summary>
> > >     /// 一个接口,表示服务降级提供者
> > >     /// </summary>
> > >     /// <typeparam name="T"></typeparam>
> > >     public interface IFallbackFactory</*out*/ T>
> > >     {
> > >         T GetFallback();
> > >         void ReleaseFallback(T fallback);
> > >     }
> > > ```
> > 
> > 
> > 好像没这功能,您是啥场景需要这个呢?
> > 这个降级功能不完善,没有熔断功能,可以集成Polly试试
> 
> 比如A调用B服务，在B服务异常时（服务不可用或者服务地址写错），需要打印错误日志，微服务框架用的spring cloud alibaba，不知道能不能用Polly

可以参考这个试试  [https://github.com/daixinkai/feign.net/tree/master/src/Feign.Polly](url)

**Comment by z514987467** [comment]
在Nuget里面没有搜到Feign.Polly，试了下Polly满足我的需求，下了源码我打包上去了
